### ISSUE TITLE
RBAC example

### ISSUE THREAD

**Issue by DerrickMartinez** [uswitch/sqs-autoscaler-controller#5]
I am running k8s 1.8.1 and I had to change somethings including RBAC to get it working. Here is my example with RBAC

```
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sqs-autoscaler-controller-role
subjects:
- kind: ServiceAccount
  name: sqs-autoscaler-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: kube-system
  name: sqs-autoscaler-controller-role
rules:
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - "aws.uswitch.com"
  resources:
  - sqsautoscalers
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - update
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: sqs-autoscaler-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sqs-autoscaler-controller
      annotations:
        iam.amazonaws.com/role: sqs_read_only
    spec:
      serviceAccountName: sqs-autoscaler-controller
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
      containers:
      - image: 12345.dkr.ecr.us-west-2.amazonaws.com/sqs-autoscaler-controller:1.0
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: us-west-2
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
          - --statsd=$(NODE_IP):30565
        name: sqs-autoscaler-controller
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
            readOnly: true
```

Another issue was with using $(NODE_NAME):30565, I was getting DNS lookup failures which was really weird. Moved to an IP.

Next I was having issues with the Root Cert, so I changed some paths and also changed the Dockerfile to:

```
FROM alpine:3.6

RUN  apk add --no-cache --update ca-certificates

ADD bin/sqs-autoscaler-controller /sqs-autoscaler-controller

ENTRYPOINT ["/sqs-autoscaler-controller"]
```
